<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\APS.Domain\APS.Domain.csproj" />
    <ProjectReference Include="..\APS.Application\APS.Application.csproj" />
    <PackageReference Include="Google.OrTools" Version="9.15.6755" />
  </ItemGroup>
</Project>
